from django.urls import path
from .views import (
    RegisterView, 
    SendOTPView, 
    ResendOTPView, 
    LoginView, 
    DashboardView,
    ForgotPasswordSendOTPView,
    ForgotPasswordVerifyOTPView,
    ForgotPasswordResetView,
    DeactivateSendOTPView,
    DeactivateView,
    ReactivateSendOTPView,
    ReactivateVerifyOTPView,
    ReactivateConfirmView,
    ChangePasswordSendOTPView,
    ChangePasswordConfirmView,
    CreatePINView,
    ChangePINView,
    ResetPINView,
    VerifyPINView,
    PinSendOTPView,
    VerifyRecipientView,
    ExecuteTransferView,
    TransactionHistoryView,
    StatementListView,
    DownloadStatementPDFView,
    EmailStatementPDFView,
    FreezeUnfreezeCardView,
    RegenerateCvvView,
    ReplaceCardView,
    AccountIdentityView
)

urlpatterns = [
    path('signup/', RegisterView.as_view(), name='signup'),
    path('send-otp/', SendOTPView.as_view(), name='send_otp'),
    path('resend-otp/', ResendOTPView.as_view(), name='resend_otp'),
    path('login/', LoginView.as_view(), name='login'),
    path('dashboard/', DashboardView.as_view(), name='dashboard'),
    path('forgot-password/send-otp/', ForgotPasswordSendOTPView.as_view(), name='forgot_password_send_otp'),
    path('forgot-password/verify-otp/', ForgotPasswordVerifyOTPView.as_view(), name='forgot_password_verify_otp'),
    path('forgot-password/reset/', ForgotPasswordResetView.as_view(), name='forgot_password_reset'),
    path('deactivate/send-otp/', DeactivateSendOTPView.as_view(), name='deactivate_send_otp'),
    path('deactivate/', DeactivateView.as_view(), name='deactivate'),
    path('reactivate/send-otp/', ReactivateSendOTPView.as_view(), name='reactivate_send_otp'),
    path('reactivate/verify-otp/', ReactivateVerifyOTPView.as_view(), name='reactivate_verify_otp'),
    path('reactivate/confirm/', ReactivateConfirmView.as_view(), name='reactivate_confirm'),
    path('change-password/send-otp/', ChangePasswordSendOTPView.as_view(), name='change_password_send_otp'),
    path('change-password/confirm/', ChangePasswordConfirmView.as_view(), name='change_password_confirm'),
    path('pin/send-otp/', PinSendOTPView.as_view(), name='pin_send_otp'),
    path('pin/create/', CreatePINView.as_view(), name='pin_create'),
    path('pin/change/', ChangePINView.as_view(), name='pin_change'),
    path('pin/reset/', ResetPINView.as_view(), name='pin_reset'),
    path('pin/verify/', VerifyPINView.as_view(), name='pin_verify'),
    path('transfer/verify/', VerifyRecipientView.as_view(), name='transfer_verify'),
    path('transfer/execute/', ExecuteTransferView.as_view(), name='transfer_execute'),
    path('transactions/', TransactionHistoryView.as_view(), name='transactions_history'),
    path('statements/', StatementListView.as_view(), name='statements_list'),
    path('statements/download/<int:year>/<int:month>/', DownloadStatementPDFView.as_view(), name='statement_download_pdf'),
    path('statements/email/<int:year>/<int:month>/', EmailStatementPDFView.as_view(), name='statement_email_pdf'),
    path('card/freeze/', FreezeUnfreezeCardView.as_view(), name='card_freeze'),
    path('card/cvv/', RegenerateCvvView.as_view(), name='card_cvv'),
    path('card/replace/', ReplaceCardView.as_view(), name='card_replace'),
    path('identity/<str:account_number>/', AccountIdentityView.as_view(), name='account_identity'),
]

